#pragma once


#define MSG_BASE						(WM_USER  + 2010)
#define XDICT_DLG_MSG_BASE				(MSG_BASE + 0)
#define MAIN_DLG_MSG_BASE				(MSG_BASE + 1000)
#define IM_DLG_MSG_BASE					(MSG_BASE + 2000)
#define LOGIN_DLG_MSG_BASE				(MSG_BASE + 3000)
#define CHAT_DLG_MSG_BASE				(MSG_BASE + 4000)
#define COMMAND_DLG_MSG_BASE			(MSG_BASE + 5000)
#define GLOBAL_MSG_BASE					(MSG_BASE + 6000)
#define CLASSROOM_DLG_MSG_BASE			(MSG_BASE + 7000)


//////////////////////////////////////////////////////////////////////////
// for CXDictDlg
#define MSG_QUERY_RESULT				(XDICT_DLG_MSG_BASE + 1)
#define MSG_HIDE_WND					(XDICT_DLG_MSG_BASE + 2)
#define MSG_INPUTCOMBOBOX_VKDOWN		(XDICT_DLG_MSG_BASE + 3)
// tool bar item clicked notify
#define MSG_TOOLBAR_ITEM_CLICKED		(XDICT_DLG_MSG_BASE + 8)	// WPARAM : ptr to item_name; LPARAM : toolbar ctrl ID
// for child control
#define MSG_INPUT_QUERY					(XDICT_DLG_MSG_BASE + 9)
#define MSG_INPUT_SEARCH				(XDICT_DLG_MSG_BASE + 10)
#define MSG_ON_QUERY_RESULT				(XDICT_DLG_MSG_BASE + 11)
#define MSG_ON_QUERY_INDEX_LIST			(XDICT_DLG_MSG_BASE + 12)
#define MSG_ON_QUERY_INDEX_RESULT		(XDICT_DLG_MSG_BASE + 13)
#define MSG_DICT_LIST_CHANGE			(XDICT_DLG_MSG_BASE + 14)
// Mini Writing Assist
#define WM_SHOW_WRITE_ASSIST			(XDICT_DLG_MSG_BASE + 15)
#define WM_MINI_SETFOUSE				(XDICT_DLG_MSG_BASE + 16)
#define WM_TRANSLATE_MINI_DLG			(XDICT_DLG_MSG_BASE + 17)
// update front page
#define WM_UPDATE_FRONTPAGE				(XDICT_DLG_MSG_BASE + 18)
#define MSG_CHANGE_CSS					(XDICT_DLG_MSG_BASE + 19)
#define MSG_RELOAD_HISTORY_RECORD		(XDICT_DLG_MSG_BASE + 20)
#define MSG_SWITCH_GRABSELECT_STATE		(XDICT_DLG_MSG_BASE + 21)
// 取词界面、迷你界面等请求XDictDlg查询
#define MSG_LOOKUP_WORD					(XDICT_DLG_MSG_BASE + 50)
#define MSG_LOOKUP_SENTENCE				(XDICT_DLG_MSG_BASE + 51)
#define MSG_LOOKUP_CHINESE				(XDICT_DLG_MSG_BASE + 52)
#define MSG_LOOKUP_TRANSLATION			(XDICT_DLG_MSG_BASE + 53)
// view发送的消息, 消息中的参数均为const wchar_t*
#define WM_FROMVIEW_DEFAULT_MENU		(XDICT_DLG_MSG_BASE + 100)	// 默认菜单
#define WM_FROMVIEW_SELECT_MENU			(XDICT_DLG_MSG_BASE + 101)	// 选中菜单
#define WM_FROMVIEW_QUERY_WORD_SENTENCE	(XDICT_DLG_MSG_BASE + 102)	// 根据当前tab页查词或句，WPARAM为要查的内容
#define WM_FROMVIEW_QUERY_CURRENT		(XDICT_DLG_MSG_BASE + 103)	// 重新查询当前tab页edit上的词或句
#define WM_FROMVIEW_READ				(XDICT_DLG_MSG_BASE + 104)	// 发音，WPARAM为要发音的单词
#define WM_FROMVIEW_QUERY_HANYU			(XDICT_DLG_MSG_BASE + 105)	// 查询汉语站，WPARAM为要查询的URL
#define WM_FROMVIEW_QUERY_SENTENCE		(XDICT_DLG_MSG_BASE + 106)	// 查询当前词的句库，WPARAM为要查询内容
#define WM_FROMVIEW_QUERY_HUIHUA		(XDICT_DLG_MSG_BASE + 107)	// Wiki情景会话查询
#define WM_FROMVIEW_HANHAN_EXPLA		(XDICT_DLG_MSG_BASE + 108)	// Wiki汉汉解释
#define WM_FROMVIEW_HUIHUA_SEARCH		(XDICT_DLG_MSG_BASE + 109)	// 会话查询, wParam为SearchID
// for dict update
#define MSG_DICT_UPDATE					(XDICT_DLG_MSG_BASE + 110)
//#define WM_MY_GETTEXT					(XDICT_DLG_MSG_BASE + 111)	// 获得密码框的文字

#define XDICT_MAINDLG_CAPTION (L"{1E8ECB6E-0EF0-40c2-8D4C-E8EDCFE7740D}~ChuankeKK") // XDict主窗口名，发送WM_REAl_QUIT_CIBA消息退出程序
#define WM_REAl_QUIT_CIBA               (XDICT_DLG_MSG_BASE + 2046)	// KKUpdate调用退出词霸
struct CheckUpdateOnExit {enum {No = 0, Yes = 1};};					// wParam for msg WM_REAl_QUIT_CIBA
#define WM_TRANSLATEINSTALLOK           (XDICT_DLG_MSG_BASE + 2048)	//翻译助手成功安装


//////////////////////////////////////////////////////////////////////////
// for CMainDlg
#define MSG_EXIT_APP					(MAIN_DLG_MSG_BASE + 1)
#define MSG_POPUP_MAINMENU				(MAIN_DLG_MSG_BASE + 2)
#define MSG_POPUP_MAINMENUEX			(MAIN_DLG_MSG_BASE + 3)
#define MSG_UPDATE_TRAYICON				(MAIN_DLG_MSG_BASE + 4)
#define WM_UPDATE_INFO_NOTIFY           (MAIN_DLG_MSG_BASE + 5)
//#define WM_ACTIVATE_CURWND				(MAIN_DLG_MSG_BASE + 6)
// 取词界面等调设置界面
#define MSG_SHOW_SETTINGDLG				(MAIN_DLG_MSG_BASE + 7)		// WPARAM : Setting Dlg Index (0, 1, 2, ...)
#define MSG_GET_GBB_UID					(MAIN_DLG_MSG_BASE + 8)
#define MSG_UPDATE_GRABSELECT_MENUITEM	(MAIN_DLG_MSG_BASE + 10)
#define MSG_OPEN_COSTCENTER				(MAIN_DLG_MSG_BASE + 11)
#define MSG_SHOW_DICTSETDLG				(MAIN_DLG_MSG_BASE + 12)	// WPARAM : Setting Dlg Index (0, 1, 2, ...)
#define MSG_EXPWARN_DLG_CLOSE			(MAIN_DLG_MSG_BASE + 13)
#define MSG_POPUP_IMMENUEX			    (MAIN_DLG_MSG_BASE + 114)


//////////////////////////////////////////////////////////////////////////
// for CIMDlg
#define MSG_UPDATE_PHOTO				(IM_DLG_MSG_BASE + 1)
#define MSG_UPDATE_USERINFO				(IM_DLG_MSG_BASE + 2)
//#define MSG_SIGNATURE_CHANGED			(IM_DLG_MSG_BASE + 3)
#define MSG_MODIFY_CLUSTER_CARD			(IM_DLG_MSG_BASE + 4)
#define MSG_AIR_SCHOOL_ENTER_ROOM    	(IM_DLG_MSG_BASE + 5)
#define MSG_CONTACTOR_OPERATE_BASE		(WM_USER + 0xFB0)
#define MSG_GET_CLASS_CREATE_URL		(IM_DLG_MSG_BASE + 1000)
#define MSG_GET_CLASS_INDEX_URL			(IM_DLG_MSG_BASE + 1001)
#define MSG_RELOAD_FRONT_PAGE			(IM_DLG_MSG_BASE + 1002)
#define MSG_GET_URL_TOKEN				(IM_DLG_MSG_BASE + 1003)

//////////////////////////////////////////////////////////////////////////
// for CLoginDlg
#define WM_LOGIN_LOGIN					(LOGIN_DLG_MSG_BASE + 1)


//////////////////////////////////////////////////////////////////////////
// for CChatDlg
#define MSG_FONT_SETTING_CHANGED			(CHAT_DLG_MSG_BASE + 1)
#define MSG_SEND_OPTION_CHANGED				(CHAT_DLG_MSG_BASE + 2)
#define MSG_EMOTION_SELECTED				(CHAT_DLG_MSG_BASE + 3)
#define MSG_EMOTIONDLG_HIDE					(CHAT_DLG_MSG_BASE + 4)
#define MSG_DELETE_MSGRECORD				(CHAT_DLG_MSG_BASE + 5)	// WPARAM(type : 1, 2, 3); LPARAM(msg id)
#define MSG_MSGRECORD_DBCLICK				(CHAT_DLG_MSG_BASE + 6) // LPARAM(msg id)
#define MSG_OUIFOREGROUNDWINDOW				(CHAT_DLG_MSG_BASE + 7)
#define MSG_CAPTURE_OPTION_CHANGED			(CHAT_DLG_MSG_BASE + 8)
#define MSG_SCREEN_CAPTURE_CALLBACK			(CHAT_DLG_MSG_BASE + 9)
#define MSG_FILETRANS_TEXTBTN_CLICKED		(CHAT_DLG_MSG_BASE + 10)
#define MSG_FILETRANS_SENDFILE_AGAIN		(CHAT_DLG_MSG_BASE + 11)
#define MSG_FILETRANS_CHANGE_SECURITY_LEVEL	(CHAT_DLG_MSG_BASE + 12)
#define MSG_TIPTAB_CLICKED					(CHAT_DLG_MSG_BASE + 13)
#define MSG_HTMLTAG_INVITE_CLASS			(CHAT_DLG_MSG_BASE + 14)
#define MSG_HTMLTAG_INVITE_CHANNEL			(CHAT_DLG_MSG_BASE + 15)
#define MSG_DISCUSS_NAME_CHANGE				MSG_SIGNATURE_CHANGED
#define	MSG_INPUTTEXT_BEGIN					(WM_USER + 0xFEC)
#define MSG_INPUTTEXT_OVER					(WM_USER + 0xFED)


//////////////////////////////////////////////////////////////////////////
// classroom dialog
#define MSG_PENCIL_POS_CHANGED				(CLASSROOM_DLG_MSG_BASE + 1)
#define MSG_CLOSE_WHITEBOARD				(CLASSROOM_DLG_MSG_BASE + 2)
#define MSG_GRAPHIC_COMPLETED				(CLASSROOM_DLG_MSG_BASE + 3)
#define MSG_ERASE_GRAPHIC					(CLASSROOM_DLG_MSG_BASE + 4)
#define MSG_ERASE_ALL_GRAPHIC				(CLASSROOM_DLG_MSG_BASE + 5)
#define MSG_BLANK_PAPER						(CLASSROOM_DLG_MSG_BASE + 6)
#define MSG_TEXTBOARD						(CLASSROOM_DLG_MSG_BASE + 7)
#define MSG_TEXTBOARD_FONTCHANGE			(CLASSROOM_DLG_MSG_BASE + 8)
#define MSG_TEXTBOARD_SAVEAS				(CLASSROOM_DLG_MSG_BASE + 9)
#define MSG_SCREEN_CAPTURE					(CLASSROOM_DLG_MSG_BASE + 10)
#define MSG_AUDIO_ERROR_NOTIFY				(CLASSROOM_DLG_MSG_BASE + 20)
#define MSG_TEACHER_CAMERA_VIDEO_ERROR		(CLASSROOM_DLG_MSG_BASE + 21)
#define MSG_FORCEEXIT_CLASSROOM				(CLASSROOM_DLG_MSG_BASE + 22)
#define MSG_CONFIRM_DEL_VISITANT			(CLASSROOM_DLG_MSG_BASE + 23)
#define MSG_ADDCOURSEWARE_ITEM				(CLASSROOM_DLG_MSG_BASE + 24)
#define MSG_ADDCOURSEWARE_FINISH			(CLASSROOM_DLG_MSG_BASE + 25)
#define MSG_CANCEL_ADDCOURSEWARE			(CLASSROOM_DLG_MSG_BASE + 26)
#define MSG_COURSE_RECORD_NOTIFY			(CLASSROOM_DLG_MSG_BASE + 27)
#define MSG_UID_TAG_RBUTTONUP				(CLASSROOM_DLG_MSG_BASE + 28)
#define MSG_LOOKUP_VIDEO					(CLASSROOM_DLG_MSG_BASE + 29)
#define MSG_UPLOAD_VIDEO					(CLASSROOM_DLG_MSG_BASE + 30)
#define MSG_GET_SCHOOL_HOMEPAGE_URL			(CLASSROOM_DLG_MSG_BASE + 40)
#define MSG_GET_SCHOOL_BRIEF_URL			(CLASSROOM_DLG_MSG_BASE + 41)
#define MSG_TEACHER_CAMERAWND_CLOSE			(CLASSROOM_DLG_MSG_BASE + 42)
#define MSG_SCREENRECORD_EXIT				(CLASSROOM_DLG_MSG_BASE + 43)
#define MSG_SCRRENRECORD_ERROR				(CLASSROOM_DLG_MSG_BASE + 44)
#define MSG_SCREENRECORD_POSCHANGE			(CLASSROOM_DLG_MSG_BASE + 45)
#define MSG_QUIZDLG_EXIT					(CLASSROOM_DLG_MSG_BASE + 50)


//////////////////////////////////////////////////////////////////////////
// IM请求数据异步返回消息
#define MSG_UPDATE_ONLINESTATE			(COMMAND_DLG_MSG_BASE + 0)
#define MSG_LOGIN_CALLBACK				(COMMAND_DLG_MSG_BASE + 1)


/////////////////////////////////////////////////////////////////
// global message
#define MSG_UPDATE_NEW_EMAIL_COUNT		(GLOBAL_MSG_BASE + 1)
#define MSG_UPDATE_PERRSONAL_NEWS_COUNT	(GLOBAL_MSG_BASE + 2)
#define MSG_ALL_HTML_DOWNLOAD_COMPLETE  (GLOBAL_MSG_BASE + 3)
#define MSG_CIBAMSGBOX_CALLBACK			(GLOBAL_MSG_BASE + 4)
#define MSG_HIPOINTS_UPDATE				(GLOBAL_MSG_BASE + 5)
#define MSG_DELETE_ADDRESSBOOKDLG		(GLOBAL_MSG_BASE + 6)
#define MSG_INIT_SELECTMEM_DLG			(GLOBAL_MSG_BASE + 7)
#define MSG_MESSAGEBOX_MAX_PERSON		(GLOBAL_MSG_BASE + 8)
#define MSG_ADDRESS_BOOK_SHOW_EDIT      (GLOBAL_MSG_BASE + 9)
#define MSG_VIDEOCTRL_ONSIZE			(GLOBAL_MSG_BASE + 10)
#define MSG_HTMLTAG_ACTION				(GLOBAL_MSG_BASE + 11)

#define MSG_CALL_NOTIFY					(GLOBAL_MSG_BASE + 12)
#define MSG_CLIENT_NOTIFY			    (GLOBAL_MSG_BASE + 13)
// #define MSG_INPUT_VOLUMN_CHAGE_NOTIFY	(GLOBAL_MSG_BASE + 14)
// #define MSG_OUTPUT_VOLUMN_CHAGE_NOTIFY	(GLOBAL_MSG_BASE + 15)
#define MSG_VEDIO_SERVER_STATUS_NOTIFY	(GLOBAL_MSG_BASE + 16)
//#define MSG_SEND_IMAGE					(GLOBAL_MSG_BASE + 14)
//#define MSG_FETCH_IMAGE					(GLOBAL_MSG_BASE + 15)